<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/04-01-multi-variable-linear-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 모두를 위한 머신러닝에서 가져왔습니다.
# Multi-variable linear regression

In [92]:
import tensorflow as tf

In [130]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [131]:
w1 = tf.Variable(tf.random.normal([1]), name='weight1')
w2 = tf.Variable(tf.random.normal([1]), name='weight2')
w3 = tf.Variable(tf.random.normal([1]), name='weight3')

b = tf.Variable(tf.random.normal([1]), name='bias')

w1 [-0.40483686] w2 [0.90496516] w3 [-0.18671575]



In [132]:
lr = tf.constant(0.0001)

In [133]:
for step in range(10):
  for i in range(5):
    hypothesis = x1_data[i] * w1 + x2_data[i] * w2 + x3_data[i] * w3 + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data[i]))

    gred1 = tf.reduce_mean((hypothesis - y_data[i]) * x1_data[i])
    gred2 = tf.reduce_mean((hypothesis - y_data[i]) * x2_data[i])
    gred3 = tf.reduce_mean((hypothesis - y_data[i]) * x3_data[i])

    w1 = w1 - lr * gred1
    w2 = w2 - lr * gred2
    w3 = w3 - lr * gred3

  if step % 10 == 0:
    print('Step: {:02d} \tCost: {}\n'.format(step, cost))
    print('gred1 {} \t gred2 {} \t gred3 {}\n'.format(gred1, gred2, gred3))
    print('w1 {} w2 {} w3 {}\n'.format(w1, w2, w3))


hypothesis: tf.Tensor([29.763046], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2568.563], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([-56227.15], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([1431406.4], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([-28288428.], shape=(1,), dtype=float32)
Step: 00 	Cost: 800243205537792.0

gred1 -2065065600.0 	 gred2 -1867045632.0 	 gred3 -1980199936.0

w1 [1932476.6] w2 [1731721.1] w3 [1841942.9]

hypothesis: tf.Tensor([4.1775424e+08], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([-8.1875436e+09], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([1.9378402e+11], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([-4.916858e+12], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([9.718406e+13], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([-1.4351745e+15], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.8127921e+16], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([-6.657359e+17], shape=(1,), dtype=float32)
hypothesis: tf.

In [52]:
# cost/loss function
# for step in range(10):
#   with tf.GradientTape() as tape:
#     hypothesis = x1_data * w1 + x2_data * w2 + x3_data * w3 + b
#     cost = tf.reduce_mean(tf.square(hypothesis - y_data))

#   gred = tape.gradient(cost,[w1,w2,w3])
#   print(gred[0])
#   print(gred[1])
#   print(gred[2])

#   w1 = w1 - lr * tf.cast(gred[0], tf.float32)
#   w2 = w2 - lr * tf.cast(gred[1], tf.float32)
#   w3 = w3 - lr * tf.cast(gred[2], tf.float32)

#   # if step % 10 == 0:
#   #   print('Step: {}\tCost: {}\t, prediction:{}'.format(step, cost, hypothesis.numpy()))

AttributeError: ignored

In [12]:
w1 = w1 - lr*gred1.numpy()

AttributeError: ignored