<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/04-03-multi-variable-linear-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# Multi-variable linear regression

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [ ]:
X = tf.constant(x_data)
Y = tf.constant(y_data)

W = tf.Variable(tf.random.normal([3,1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [ ]:
lr = 0.00001

In [ ]:
# for step in range(1):
#   with tf.GradientTape() as tape:
#     # cost/loss function
#     cost = tf.reduce_mean(tf.square(hypothesis - Y))
  
#   gred = tape.gradient(cost, [W,b])
#   W = W - lr * gred[0]
#   b = b - lr * gred[1]

#   # if (step % 10) == 0:
#   #   print('Step: {} \t cost: {}\n'.format(step, cost))

In [ ]:
for step in range(2000):
  hypothesis = tf.matmul(X, W) + b
  cost = tf.reduce_mean(tf.square(hypothesis - Y))
  w_gredient = tf.reduce_mean((hypothesis-Y) * X)
  b_gredient = tf.reduce_mean((hypothesis-Y))
  W = W - lr * w_gredient
  b = b - lr * b_gredient

  if (step % 10) == 0:
    print('Step: {} \t cost: {}\n'.format(step, cost))

In [82]:
#prediction
predict_y = tf.matmul(X, W) + b
predict_y.numpy()

array([[150.81482],
       [185.286  ],
       [180.67537],
       [194.40799],
       [144.28491]], dtype=float32)

In [83]:
Y

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)>