<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/08-01-tensor-manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# Tensor Manipulation

In [5]:
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=4)

# Simple array

In [6]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


# Shape, Rank, Axis

In [13]:
t = tf.constant([1,2,3,4])
tf.shape(t).numpy()

array([4], dtype=int32)

In [14]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).numpy()

array([1, 2, 3, 4], dtype=int32)

In [16]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

# Matmul VS multiply

In [18]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).numpy()

array([[12.]], dtype=float32)

In [19]:
(matrix1*matrix2).numpy()

array([[6., 6.],
       [6., 6.]], dtype=float32)

# Watch out broadcasting

In [21]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).numpy()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [22]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).numpy()

array([[5., 5.]], dtype=float32)

# Random values for variable initializations

In [24]:
tf.random.normal([3]).numpy()

array([ 0.08841158, -0.204986  , -0.03974847], dtype=float32)

In [27]:
tf.random.uniform([2]).numpy()

array([0.18386662, 0.48262644], dtype=float32)

In [28]:
tf.random.uniform([2,3]).numpy()

array([[0.7526654 , 0.06489861, 0.7455903 ],
       [0.17594862, 0.41897786, 0.6446935 ]], dtype=float32)

# Reduce Mean/Sum

In [29]:
tf.reduce_mean([1, 2], axis=0).numpy()

1

In [30]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).numpy()

2.5

In [31]:
tf.reduce_mean(x, axis=0).numpy()

array([2., 3.], dtype=float32)

In [32]:
tf.reduce_mean(x, axis=1).numpy()

array([1.5, 3.5], dtype=float32)

In [33]:
tf.reduce_mean(x, axis=-1).numpy()

array([1.5, 3.5], dtype=float32)

In [34]:
tf.reduce_sum(x).numpy()

10.0

In [35]:
tf.reduce_sum(x, axis=0).numpy()

array([4., 6.], dtype=float32)

In [37]:
tf.reduce_sum(x, axis=-1).numpy()

array([3., 7.], dtype=float32)

In [38]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).numpy()

5.0

# Argmax with axis

In [39]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).numpy()

array([1, 0, 0])

In [40]:
tf.argmax(x, axis=1).numpy()

array([2, 0])

In [41]:
tf.argmax(x, axis=-1).numpy()

array([2, 0])

# Reshape, squeeze, expand_dims

In [42]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [43]:
tf.reshape(t, shape=[-1, 3]).numpy()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
tf.reshape(t, shape=[-1, 1, 3]).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [45]:
tf.squeeze([[0], [1], [2]]).numpy()

array([0, 1, 2], dtype=int32)

In [46]:
tf.expand_dims([0, 1, 2], 1).numpy()

array([[0],
       [1],
       [2]], dtype=int32)

# One hot

In [47]:
tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [48]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# Casting