<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/12-0-rnn-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# RNN - Recurrent Neural Network

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

In [3]:
x_data = np.array([[h]], dtype=np.float32) # x_data = [[[1,0,0,0]]]
x_data.shape

(1, 1, 4)

In [4]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(hidden_size)
print(cell.output_size, cell.state_size)

rnn = tf.keras.layers.RNN(cell)
outputs = rnn(x_data)
print(outputs)

2 2
tf.Tensor([[-0.71143895  0.65140927]], shape=(1, 2), dtype=float32)


![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [10]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)
x_data.shape

(1, 5, 4)

In [19]:
hidden_size = 2

cell = tf.keras.layers.SimpleRNNCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('x_data.shape: ', x_data.shape)
print('x_data\n',x_data)
print('outputs.shape:',outputs.shape)
print('outputs\n', outputs.numpy())

x_data.shape:  (1, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
outputs.shape: (1, 5, 2)
outputs
 [[[-0.43584016 -0.19528571]
  [-0.27383873 -0.28374147]
  [-0.46921247  0.6649571 ]
  [-0.8986007   0.5682411 ]
  [-0.75478137  0.5250363 ]]]


![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

In [22]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                    [e, o, l, l, l],
                    [l, l, e, e, l]], dtype=np.float32)
print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

x_data.shape: (3, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]


In [23]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

output.shape: (3, 5, 2)
output
 tf.Tensor(
[[[-0.6283487  -0.10043665]
  [-0.42166    -0.6076374 ]
  [-0.59528446  0.8952497 ]
  [-0.76627594 -0.0296947 ]
  [-0.05682485  0.33300442]]

 [[ 0.16369599 -0.70083   ]
  [ 0.73359424  0.72560036]
  [ 0.31671834  0.00404254]
  [-0.01340577  0.6435583 ]
  [-0.38575423  0.16017036]]

 [[-0.31678995  0.66427547]
  [-0.611129    0.17010818]
  [-0.4301399  -0.75135595]
  [-0.18425854 -0.07760013]
  [-0.4648613   0.7145149 ]]], shape=(3, 5, 2), dtype=float32)


In [ ]:
# One cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch: 3
batch_size = 3
x_data = np.array([[h, e, l, l, o],
                  [e, o, l, l, l],
                  [l, l, e, e, l]], dtype=np.float32)

print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

hidden_size = 2
cell = tf.keras.layers.LSTMCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

In [28]:
# One LSTM cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                    [e, o, l, l, l],
                    [l, l, e, e, l]], dtype=np.float32)

print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

hidden_size = 2
batch_size = 3
cell = tf.keras.layers.LSTMCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

x_data.shape: (3, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]
output.shape: (3, 5, 2)
output
 tf.Tensor(
[[[ 0.08374617  0.01288428]
  [ 0.21227686 -0.00973273]
  [ 0.18807651 -0.03891007]
  [ 0.21287988 -0.06462617]
  [ 0.15266597 -0.04557656]]

 [[ 0.1393305  -0.02442168]
  [ 0.00507545  0.00614549]
  [ 0.06877099 -0.02814475]
  [ 0.12219477 -0.05550514]
  [ 0.16447954 -0.07805086]]

 [[ 0.0665693  -0.03230015]
  [ 0.12058748 -0.0589099 ]
  [ 0.2710358  -0.09537897]
  [ 0.34898314 -0.11715575]
  [ 0.2688601  -0.10865677]]], shape=(3, 5, 2), dtype=float32)
