<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/13-rnn-lotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# RNN-lotto

In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
url = 'https://raw.githubusercontent.com/dantae74/machine-learning/main/dataset/lotto.csv'
df = pd.read_csv(url)

In [3]:
df.head()

seq       date  num            won   1   2   3   4   5   6
0  964  2021.5.22   10  2,345,861,063   6  21  36  38  39  43
1  963  2021.5.15   15  1,476,478,125   6  12  19  23  34  42
2  962   2021.5.8   12  1,940,906,094   1  18  28  31  34  43
3  961   2021.5.1    9  2,575,231,209  11  20  29  31  33  42
4  960  2021.4.24   10  2,401,133,213   2  18  24  30  32  45

In [4]:
df = df.sort_values('seq', ascending=True)

In [5]:
df.head()

seq        date  num            won   1   2   3   4   5   6
963    1   2002.12.7    0              0  10  23  29  33  37  40
962    2  2002.12.14    1  2,002,006,800   9  13  21  25  32  42
961    3  2002.12.21    1  2,000,000,000  11  16  19  21  27  31
960    4  2002.12.28    0              0  14  27  30  31  40  42
959    5    2003.1.4    0              0  16  24  29  40  41  42

In [6]:
x = np.zeros(shape=(1,45), dtype=float)

In [7]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
X = np.array(np.zeros(shape=(1,45), dtype=float))
for i in range(df.shape[0]):
  for j in range(6):
    col = df.iloc[i][str(j+1)]
    x[0][col-1] += 1.0
    # if i < 5:
    #   print('x:', x)
  X = np.append(X, x, axis=0)

In [9]:
X.shape

(965, 45)

In [10]:
X[500]

array([76., 65., 70., 72., 68., 57., 61., 68., 54., 69., 66., 60., 69.,
       72., 65., 62., 73., 70., 70., 83., 62., 60., 60., 67., 69., 69.,
       75., 56., 64., 63., 67., 57., 62., 78., 63., 70., 81., 57., 67.,
       83., 55., 64., 66., 63., 72.])

In [11]:
df_y = df[['1','2','3','4','5','6']]

In [12]:
df_y.shape

(964, 6)

In [13]:
Y = df_y.values

In [14]:
Y.shape

(964, 6)

In [15]:
Y[0]

array([10, 23, 29, 33, 37, 40])