<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/08-01-tensor-manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# Tensor Manipulation

In [1]:
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=4)

# Simple array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


# Shape, Rank, Axis

In [4]:
t = tf.constant([1,2,3,4])
tf.shape(t).numpy()

array([4], dtype=int32)

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).numpy()

array([1, 2, 3, 4], dtype=int32)

In [7]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

# Matmul VS multiply

In [8]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).numpy()

array([[12.]], dtype=float32)

In [9]:
(matrix1*matrix2).numpy()

array([[6., 6.],
       [6., 6.]], dtype=float32)

# Watch out broadcasting

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).numpy()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).numpy()

array([[5., 5.]], dtype=float32)

# Random values for variable initializations

In [12]:
tf.random.normal([3]).numpy()

array([-0.5827057 , -1.4170836 , -0.27478746], dtype=float32)

In [13]:
tf.random.uniform([2]).numpy()

array([0.38380265, 0.11822426], dtype=float32)

In [14]:
tf.random.uniform([2,3]).numpy()

array([[0.5190456 , 0.8546134 , 0.20357311],
       [0.5347223 , 0.224702  , 0.1844207 ]], dtype=float32)

# Reduce Mean/Sum

In [15]:
tf.reduce_mean([1, 2], axis=0).numpy()

1

In [16]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).numpy()

2.5

In [17]:
tf.reduce_mean(x, axis=0).numpy()

array([2., 3.], dtype=float32)

In [18]:
tf.reduce_mean(x, axis=1).numpy()

array([1.5, 3.5], dtype=float32)

In [19]:
tf.reduce_mean(x, axis=-1).numpy()

array([1.5, 3.5], dtype=float32)

In [20]:
tf.reduce_sum(x).numpy()

10.0

In [21]:
tf.reduce_sum(x, axis=0).numpy()

array([4., 6.], dtype=float32)

In [22]:
tf.reduce_sum(x, axis=-1).numpy()

array([3., 7.], dtype=float32)

In [23]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).numpy()

5.0

# Argmax with axis

In [24]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).numpy()

array([1, 0, 0])

In [25]:
tf.argmax(x, axis=1).numpy()

array([2, 0])

In [26]:
tf.argmax(x, axis=-1).numpy()

array([2, 0])

# Reshape, squeeze, expand_dims

In [27]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [28]:
tf.reshape(t, shape=[-1, 3]).numpy()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
tf.reshape(t, shape=[-1, 1, 3]).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [30]:
tf.squeeze([[0], [1], [2]]).numpy()

array([0, 1, 2], dtype=int32)

In [31]:
tf.expand_dims([0, 1, 2], 1).numpy()

array([[0],
       [1],
       [2]], dtype=int32)

# One hot

In [32]:
tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [33]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# Casting

In [34]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy()

array([1, 2, 3, 4], dtype=int32)

In [35]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).numpy()

array([1, 0, 1, 0], dtype=int32)

# Stack

In [36]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [37]:
tf.stack([x, y, z], axis=1).numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Ones like and Zeros like

In [38]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [39]:
tf.zeros_like(x).numpy()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# Zip

In [40]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [41]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


# Tranpose

In [42]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [46]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(t1.shape)
pp.pprint(t1.numpy())

TensorShape([2, 2, 3])
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [47]:
t1 = tf.transpose(t1, [1, 0, 2])
pp.pprint(t1.shape)
pp.pprint(t1.numpy())

TensorShape([2, 2, 3])
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [48]:
t1 = tf.transpose(t, [1, 2, 0])
pp.pprint(t1.shape)
pp.pprint(t1.numpy())

TensorShape([2, 3, 2])
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [49]:
t1 = tf.transpose(t1, [2, 0, 1])
pp.pprint(t1.shape)
pp.pprint(t1.numpy())

TensorShape([2, 2, 3])
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
