<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/09-03-xor-nn-deep-wide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# XOR (deep and wide)

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [3]:
print(x_data.shape)
print(y_data.shape)

(4, 2)
(4, 1)


In [4]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=16, input_dim=2, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=16, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=16, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=16, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [5]:
# SGD not working very well due to vanishing gradient problem, switched to Adam for now
# or you may use activation='relu', study chapter 10 to know more on vanishing gradient problem.
tf.model.compile(loss='binary_crossentropy', optimizer=tf.optimizers.Adam(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                48        
_________________________________________________________________
dense_1 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_2 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_3 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 17        
Total params: 881
Trainable params: 881
Non-trainable params: 0
_________________________________________________________________


In [6]:
history = tf.model.fit(x_data, y_data, epochs=5000, verbose=0)

In [7]:
predictions = tf.model.predict(x_data)
print('Prediction: \n', predictions)

Prediction: 
 [[2.3640048e-06]
 [9.9999952e-01]
 [9.9999952e-01]
 [2.3283201e-06]]


In [8]:
score = tf.model.evaluate(x_data, y_data)
print('Accuracy: ', score[1])

1/1 [==============================] - 0s 175ms/step - loss: 1.4043e-06 - accuracy: 1.0000
Accuracy:  1.0


In [9]:
print("Accuracy: {0}, loss: {1}".format(history.history['accuracy'][-1], history.history['loss'][-1]))

Accuracy: 1.0, loss: 1.4050565368961543e-06


In [10]:
pred = tf.model.predict(x_data)

print("Hypothesis:\n{} \n\nPredict:\n {}".format(pred, tf.cast(pred > 0.5, dtype=tf.int32)))

Hypothesis:
[[2.3640048e-06]
 [9.9999952e-01]
 [9.9999952e-01]
 [2.3283201e-06]] 

Predict:
 [[0]
 [1]
 [1]
 [0]]
