<a href="https://colab.research.google.com/github/dantae74/machine-learning/blob/main/12-0-rnn-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모두를 위한 머신러닝에서 가져왔습니다.
# RNN - Recurrent Neural Network

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

In [3]:
x_data = np.array([[h]], dtype=np.float32) # x_data = [[[1,0,0,0]]]
x_data.shape

(1, 1, 4)

In [4]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(hidden_size)
print(cell.output_size, cell.state_size)

rnn = tf.keras.layers.RNN(cell)
outputs = rnn(x_data)
print(outputs)

2 2
tf.Tensor([[-0.22900037  0.02706629]], shape=(1, 2), dtype=float32)


![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [5]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)
x_data.shape

(1, 5, 4)

In [6]:
hidden_size = 2

cell = tf.keras.layers.SimpleRNNCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('x_data.shape: ', x_data.shape)
print('x_data\n',x_data)
print('outputs.shape:',outputs.shape)
print('outputs\n', outputs.numpy())

x_data.shape:  (1, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
outputs.shape: (1, 5, 2)
outputs
 [[[ 0.5351104  -0.45134276]
  [ 0.9081904  -0.25200114]
  [ 0.7423204  -0.4054174 ]
  [ 0.7049074  -0.5662117 ]
  [ 0.07460041 -0.02403957]]]


![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

In [7]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                    [e, o, l, l, l],
                    [l, l, e, e, l]], dtype=np.float32)
print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

x_data.shape: (3, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]


In [8]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

output.shape: (3, 5, 2)
output
 tf.Tensor(
[[[ 0.17790361 -0.54264104]
  [ 0.28286585  0.4627645 ]
  [ 0.58758587 -0.8537928 ]
  [ 0.96234924 -0.72159994]
  [ 0.8323494  -0.8119849 ]]

 [[-0.26463547  0.37896368]
  [-0.34197372 -0.52121013]
  [ 0.8459275  -0.24676263]
  [ 0.91638964 -0.8910948 ]
  [ 0.97406626 -0.82818776]]

 [[ 0.73805386 -0.6645264 ]
  [ 0.95466954 -0.81218547]
  [ 0.7151842  -0.05379999]
  [ 0.11627071 -0.20161478]
  [ 0.8270875  -0.6679907 ]]], shape=(3, 5, 2), dtype=float32)


In [9]:
# One cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch: 3
batch_size = 3
x_data = np.array([[h, e, l, l, o],
                  [e, o, l, l, l],
                  [l, l, e, e, l]], dtype=np.float32)

print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

hidden_size = 2
cell = tf.keras.layers.LSTMCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

x_data.shape: (3, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]
output.shape: (3, 5, 2)
output
 tf.Tensor(
[[[ 0.02604437 -0.04174869]
  [-0.06665134  0.11647929]
  [-0.13186786  0.18383867]
  [-0.17293626  0.22077441]
  [-0.37229422  0.2953368 ]]

 [[-0.0876151   0.13628949]
  [-0.32301748  0.23115537]
  [-0.2753936   0.21105373]
  [-0.2636674   0.22845747]
  [-0.2615388   0.23980086]]

 [[-0.04157986  0.12110959]
  [-0.0999819   0.18943842]
  [-0.17613894  0.24901496]
  [-0.25639784  0.2787782 ]
  [-0.32864764  0.27022317]]], shape=(3, 5, 2), dtype=float32)


In [10]:
# One LSTM cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                    [e, o, l, l, l],
                    [l, l, e, e, l]], dtype=np.float32)

print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

hidden_size = 2
batch_size = 3
cell = tf.keras.layers.LSTMCell(hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

x_data.shape: (3, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]
output.shape: (3, 5, 2)
output
 tf.Tensor(
[[[-0.11744881  0.22660132]
  [-0.01603263  0.03829354]
  [-0.13729665 -0.03501374]
  [-0.19175063 -0.09009358]
  [-0.25154144 -0.1549938 ]]

 [[ 0.05424933 -0.10501748]
  [-0.0807168  -0.14797528]
  [-0.12523228 -0.15321334]
  [-0.16798863 -0.18754506]
  [-0.18894862 -0.21378529]]

 [[-0.11837836 -0.06318909]
  [-0.17681633 -0.11405402]
  [-0.0274756  -0.19737296]
  [ 0.05300308 -0.24074514]
  [-0.03073469 -0.22371566]]], shape=(3, 5, 2), dtype=float32)


In [11]:
# Multi-RNN Cell
# One LSTM cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                    [e, o, l, l, l],
                    [l, l, e, e, l]], dtype=np.float32)

print('x_data.shape:', x_data.shape)
print('x_data\n', x_data)

cells = [tf.keras.layers.LSTMCell(2),tf.keras.layers.LSTMCell(2)]
rnn = tf.keras.layers.RNN(cells, return_sequences=True)
outputs = rnn(x_data)
print('output.shape:', outputs.shape)
print('output\n', outputs)

x_data.shape: (3, 5, 4)
x_data
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]
output.shape: (3, 5, 2)
output
 tf.Tensor(
[[[-0.00328385 -0.00498021]
  [-0.02204843 -0.01105582]
  [-0.02221465 -0.03115025]
  [-0.01131996 -0.04904044]
  [-0.01119103 -0.04638953]]

 [[-0.01828635 -0.00431069]
  [-0.03011497 -0.0019164 ]
  [-0.02915225 -0.0184859 ]
  [-0.01725354 -0.03712998]
  [ 0.00035258 -0.05064106]]

 [[ 0.00920157 -0.01294163]
  [ 0.02321314 -0.02586439]
  [ 0.00709282 -0.02929218]
  [-0.01673964 -0.03222521]
  [-0.01958312 -0.04839086]]], shape=(3, 5, 2), dtype=float32)


In [25]:
# Padding and Masking
# https://www.tensorflow.org/guide/keras/masking_and_padding

# One LSTM cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = [[h, e, l, l, o],
                    [h, e],
                    [e, l, l, o]]

print('x_data\n', x_data)

padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    x_data, padding="post"
)

print('padded_input\n', padded_inputs)

embedding = tf.keras.layers.Embedding(input_dim=4, output_dim=2, mask_zero=True)
masked_output = embedding(padded_inputs)

print(masked_output._keras_mask)

x_data
 [[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 1]], [[1, 0, 0, 0], [0, 1, 0, 0]], [[0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 1]]]
padded_input
 [[[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[1 0 0 0]
  [0 1 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 1 0 0]
  [0 0 1 0]
  [0 0 1 0]
  [0 0 0 1]
  [0 0 0 0]]]
tf.Tensor(
[[[ True False False False]
  [False  True False False]
  [False False  True False]
  [False False  True False]
  [False False False  True]]

 [[ True False False False]
  [False  True False False]
  [False False False False]
  [False False False False]
  [False False False False]]

 [[False  True False False]
  [False False  True False]
  [False False  True False]
  [False False False  True]
  [False False False False]]], shape=(3, 5, 4), dtype=bool)
